### PR TITLE
Fix UI panel behavior for attendance/clear/delete commands

### LINKED ISSUE #152: [PE-D][Tester A] Command "attendance" does not update GUI
Using the ```attendance /absent t0000001a``` does not update the GUI of the person we are currently viewing.

**Expected**
 ```attendance /absent t0000001a``` should increase the value of "days since hire" after execution
**Actual behavior**
GUI is not updated until we use the "view" command to view the employee's details again

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: mogmyij/ped#4

### LINKED ISSUE #155: [PE-D][Tester B] Bug: Clearing/Deleting users does not change right view window
-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: pranavyey/ped#10

### PR DESCRIPTION
**Pull request by wilsonh0**
Changes made:

- Added `clearDetailsPanel` flag to `CommandResult.java` 
- Added `handleClearDetails()` method and updated logic using `PersonDetailsPanel.java`'s helper methods in `MainWindow.java`. 

  - `attendance`: Now refreshes UI while maintaining current view (fixes #152)
  - `delete`: Clears panel only if person being deleted is being displayed on the panel. (fixes #155)
  - `clear`: Always clears panel (fixes #155)

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -220,9 +230,15 @@ private CommandResult executeCommand(String commandText) throws CommandException
                 rightPane.getChildren().add(personDetailsPanel.getRoot());
             }
 
-            // If the command result contains a person, update the details panel
-            if (commandResult.getPersonToView() != null) {
-                personDetailsPanel.setPerson(commandResult.getPersonToView());
+            if (commandResult.isClearDetailsPanel()) {
+                handleClearDetailsPanel(commandResult);
+            } else {
+                // If the command result contains a person, update the details panel
```
Comment (senshir) [inline src/main/java/seedu/address/ui/MainWindow.java:236]: Looks pretty good to me

**Comment by senshir** [comment]
Code looks fine, if it works on ur system then I think can merge already?
