### PR TITLE
Fix issue with automatic conversion of invalid dates in leave command

### LINKED ISSUE #78: Bug with Leave command
Dates not working correctly:
For months with no 31st, or feb with no 29-31, we get a wrong start (end is correct, screenshot shows wrong)

`leave add 3 /start 2025-02-31 /end 2025-03-01 /reason sick leave
`
Image

stored as 28th feb

Image

### PR DESCRIPTION
**Pull request by wilsonh0**
The DateFormatter previously defaulted to ResolverStyle.SMART, which allowed invalid dates to automatically convert to valid ones.

Changes made:

- Changed ResolverStyle from SMART to STRICT to enforce stricter date validation. (closes #78)
- Improved error messages to provide clearer feedback when invalid dates are detected.
- Added constraints on year values to ensure they remain within a reasonable range.
- Added test cases to check for invalid dates in a month.

**You might have to delete the previous data file "addressbook.json" to reset the addressbook as it will fail to load invalid dates.**

### CODE REVIEW

File: src/main/java/seedu/address/model/leave/Leave.java [hunk 1]
```diff
@@ -5,18 +5,31 @@
...
-            + "Start date >= end date.";
-    public static final String MESSAGE_CONSTRAINTS = "Leave dates should be in the format of yyyy-MM-dd.\n"
-            + "Start date should be before end date.\n"
-            + "Reason should not be empty.";
-    private static final DateTimeFormatter DateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
+
+
+    public static final DateTimeFormatter DATE_FORMATER = DateTimeFormatter
+            .ofPattern("uuuu-MM-dd")
+            .withResolverStyle(ResolverStyle.STRICT);
```
Comment (aaronlim02) [inline src/main/java/seedu/address/model/leave/Leave.java:32]: LGTM

File: src/main/java/seedu/address/model/leave/Leave.java [hunk 2]
```diff
@@ -5,18 +5,31 @@
...
+    public static final String DATE_CONSTRAINTS =
+            "Please ensure your dates meet all these requirements:\n"
+                    + "1. FORMAT: Must use yyyy-MM-dd (e.g., 2025-02-28)\n"
+                    + "2. YEAR RANGE: Must be between " + MIN_YEAR + " and " + MAX_YEAR + "\n"
+                    + "3. VALID DATE: Must be a real calendar date\n"
+                    + "   - February has 28 days (29 in leap years)\n"
+                    + "   - April, June, September, November have 30 days\n"
+                    + "   - Other months have 31 days\n"
+                    + "4. DATE ORDER: Start date must be on or before end date";
+
```
Comment (aaronlim02) [inline src/main/java/seedu/address/model/leave/Leave.java:26]: Error message seems good

File: src/test/java/seedu/address/model/leave/LeaveTest.java [hunk 3]
```diff
@@ -111,4 +110,10 @@ public void formattedDates() {
         assertEquals(VALID_FORMATTED_START_DATE, leave.getFormattedStartDate());
         assertEquals(VALID_FORMATTED_END_DATE, leave.getFormattedEndDate());
     }
+
+    @Test
+    public void testInvalidDate() {
+        assertFalse(Leave.isValidDate("2025-02-30")); // February 30th should be invalid
+        assertFalse(Leave.isValidDate("2025-04-31")); // April 31st should be invalid
+    }
```
Comment (aaronlim02) [inline src/test/java/seedu/address/model/leave/LeaveTest.java:118]: I think invalid leap days can be tested as well (e.g. 2025-02-29)

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -178,21 +180,46 @@ public static Leave parseLeave(String leaveStart, String leaveEnd, String reason
...
         return new Leave(leaveStart, leaveEnd, reason);
     }
 
+    // Helper method for parseLeave to check if a date is within the valid range
+    private static void validateYear(LocalDate date, String fieldName) throws ParseException {
+        int year = date.getYear();
+        if (year < Leave.MIN_YEAR || year > Leave.MAX_YEAR) {
+            throw new ParseException(String.format("%s: Year must be between %d and %d.\n%s",
+                    fieldName, Leave.MIN_YEAR, Leave.MAX_YEAR, Leave.DATE_CONSTRAINTS));
+        }
```
Comment (aaronlim02) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:220]: LGTM

**Review by aaronlim02 — COMMENTED** [review]
Can consider leap days in testcases. Else LGTM!
