### PR TITLE
Fix duplicate NRIC issue

### LINKED ISSUE #89: Add command allows adding of multiple people with duplicate NRIC
Steps:
Using the example from the add command, repeatedly add while changing the name slightly

Image

Result:
Image

From the feature list in the project notes, it should be NRIC which is the unique identifier rather than name

Image

### LINKED ISSUE #90: Edit command allows editing of a person's NRIC to one that already exists
Steps:
Edit **n** /nric T0000001A

Result:

Image

Currently, it stills checks based on name

Image

From the feature list in the project notes, NRIC should be the unique identifier

Image

### PR DESCRIPTION
**Pull request by aaronlim02**
Changes made:
- isSamePerson method in Person.java now looks at NRIC when considering duplicate
- Resolved duplicate NRIC in TypicalPersons.java

closes #90
This change closes #89 as well since the add command checks for model.hasPerson which uses the isSamePerson method

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Person.java [hunk 1]
```diff
@@ -155,7 +155,7 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-            && otherPerson.getName().equals(getName());
+            && otherPerson.getNric().equals(getNric());
```
Comment (wilsonh0) [inline src/main/java/seedu/address/model/person/Person.java:158]: LGTM
